services:
  - type: web
    plan: free
    name: Notes
    rootDir: backend
    runtime: node
    repo: https://github.com/darkrho/first-api
    buildCommand: "npm install"
    startCommand: "npm run start"

envVars:
  - key: PORT
    value: 3001
